# Generated by Django 3.2.25 on 2026-08-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20260806_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='interior_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
