# Generated by Django 3.2.25 on 2026-08-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20260814_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resort',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='interior_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
