# Generated by Django 3.2.25 on 2026-08-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20260814_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resort',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='interior_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='images/'),
        ),
    ]
