# Generated by Django 6.0.7 on 2026-08-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20260814_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(help_text='e.g. home_hero, villas_hero, experiences_hero, wellness_hero, dining_hero, weddings_hero, membership_hero, sustainability_hero', max_length=100, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('subtitle', models.CharField(blank=True, default='', max_length=300)),
                ('image', models.ImageField(max_length=500, upload_to='images/')),
            ],
        ),
    ]
