# Generated by Django 6.0.7 on 2026-08-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, help_text="Upload custom banner image. Check '[x] Clear' or leave empty to use default website image.", max_length=500, null=True, upload_to='images/'),
        ),
    ]
