# Generated by Django 6.0.7 on 2026-08-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('wellness', 'Wellness & Spa'), ('dining', 'Fine Dining & Culinary'), ('experiences', 'Experiences & Adventures'), ('general', 'General Resort Service')], db_index=True, default='general', max_length=50),
        ),
    ]
